<?php
$startDate = $_GET['start'] ?? '2025-03-01';
$endDate = $_GET['end'] ?? '2025-03-31';

$storeName = "Your Store Name";
$storeAddress = "123 Business Road, City";
$storePhone = "017XXXXXXXX";

// Dummy data again — same as above
$products = [
    ['name' => 'Product A', 'code' => 'A001', 'present_stock' => 50, 'stock_in' => 100, 'stock_out' => 50, 'profit' => 5000],
    ['name' => 'Product B', 'code' => 'B002', 'present_stock' => 20, 'stock_in' => 70, 'stock_out' => 50, 'profit' => 3000],
    ['name' => 'Product C', 'code' => 'C003', 'present_stock' => 100, 'stock_in' => 150, 'stock_out' => 50, 'profit' => 7000],
];
?>

<!DOCTYPE html>
<html>
<head>
    <title>Stock Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 14px; margin: 30px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #000; padding: 8px; text-align: center; }
        th { background-color: #f0f0f0; }
        footer { position: fixed; bottom: 10px; left: 0; right: 0; text-align: center; font-size: 12px; }
    </style>
</head>
<body>

<h2 style="text-align: center;">Stock Report</h2>

<p><strong>Store Name:</strong> <?= $storeName ?></p>
<p><strong>Address:</strong> <?= $storeAddress ?></p>
<p><strong>Phone:</strong> <?= $storePhone ?></p>
<p><strong>Report Type:</strong> Stock Profit Report</p>
<p><strong>Date Range:</strong> <?= $startDate ?> to <?= $endDate ?></p>

<table>
    <thead>
        <tr>
            <th>Product Name</th>
            <th>Code</th>
            <th>Present Stock</th>
            <th>Total Stock In</th>
            <th>Total Stock Out</th>
            <th>Profit (৳)</th>
        </tr>
    </thead>
    <tbody>
        <?php
        $total_in = $total_out = $total_profit = 0;
        foreach ($products as $p):
            $total_in += $p['stock_in'];
            $total_out += $p['stock_out'];
            $total_profit += $p['profit'];
        ?>
        <tr>
            <td><?= $p['name'] ?></td>
            <td><?= $p['code'] ?></td>
            <td><?= $p['present_stock'] ?></td>
            <td><?= $p['stock_in'] ?></td>
            <td><?= $p['stock_out'] ?></td>
            <td><?= number_format($p['profit']) ?></td>
        </tr>
        <?php endforeach; ?>
        <tr style="font-weight: bold;">
            <td colspan="3">Total</td>
            <td><?= $total_in ?></td>
            <td><?= $total_out ?></td>
            <td><?= number_format($total_profit) ?></td>
        </tr>
    </tbody>
</table>

<footer>
    Generated by Store Management App | <?= date('Y-m-d') ?>
</footer>

</body>
</html>
